services:
  ohlcv-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    ports:
      - 5432:5432
    volumes:
      - ohlcv-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_DB}'"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - shared-network

  ohlcv-redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - shared-network

volumes:
  ohlcv-db-volume:

networks:
    shared-network:
      external: true